// Hedvig

data =
    {
        imagePath: "../img",
        year: "årstall",
        type: "boligtype",
        location: "beliggenhet",
        files:
            [
                {
                    fileName: "bolig_meto.jpg",
                    year: "2012",
                    type: "bolig",
                    location: "bryne",
                },
                {
                    fileName: "naering_hordatun.jpg",
                    year: "2010",
                    type: "naering",
                    location: "røldal",
                },
                {
                    fileName: "fritidsbolig_osthusvik.jpg",
                    year: "2010",
                    type: "fritidsbolig",
                    location: "østhusvik",
                },
                {
                    fileName: "bolig_myklebust.jpg",
                    year: "2011",
                    type: "bolig",
                    location: "nordsjøen",
                },
                {
                    fileName: "enebolig_madlavollvegen.jpg",
                    year: "2011",
                    type: "enebolig",
                    location: "madlavollveien",
                },
                {
                    fileName: "fritidsbolig_sirdal",
                    year: "2011",
                    type: "fritidsbolig",
                    location: "",
                },
                {
                    fileName: "img/bolig_ryggstraen.jpg",
                    year: "2012",
                    type: "bolig",
                    location: "",
                },
                {
                    fileName: "img/enebolig_hellevegen.JPG",
                    year: "2012",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/enebolig_stadionveien.JPG",
                    year: "2012",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/fritidsbolig_bergtun_01.jpg",
                    year: "2012",
                    type: "fritidsbolig",
                    location: "",
                },
                {
                    fileName: "img/ideer_pedersgata_01.jpg",
                    year: "2012",
                    type: "ideer",
                    location: "",
                },
                {
                    fileName: "img/naering_mellombygget_01.jpg",
                    year: "2013",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/enebolig_friggsgate.jpg",
                    year: "2013",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/fritidsbolig_li.jpg",
                    year: "2013",
                    type: "fritidsbolig",
                    location: "",
                },
                {
                    fileName: "img/mindrebygg_forusvaagen.jpg",
                    year: "2013",
                    type: "mindre_bygg",
                    location: "",
                },
                {
                    fileName: "img/mindrebygg_eiganesveien.jpg",
                    year: "2013",
                    type: "mindre_bygg",
                    location: "",
                },
                {
                    fileName: "img/bolig_grandkvartalet_01.jpg",
                    year: "2014",
                    type: "bolig",
                    location: "",
                },
                {
                    fileName: "img/enebolig_holbergsgate.jpg",
                    year: "2014",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/naering_dansesaler.jpg",
                    year: "2015",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/naering_mostun.jpg",
                    year: "2015",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/naering_zetlitzveien.JPG",
                    year: "2015",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/enebolig_mariahaugen.jpg",
                    year: "2015",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/fritidsbolig_kyrkjoy.jpg",
                    year: "2015",
                    type: "fritidsbolig",
                    location: "",
                },
                {
                    fileName: "img/mindrebygg_brattaasveien_01.jpg",
                    year: "2015",
                    type: "mindre_bygg",
                    location: "",
                },
                {
                    fileName: "img/naering_emmaus.JPG",
                    year: "2016",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/naering_fransk_barnehage.jpg",
                    year: "2016",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/naering_tastarustaa.JPG",
                    year: "2016",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/enebolig_gitlesmauet.jpg",
                    year: "2016",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/enebolig_forusvaagen_01.jpg",
                    year: "2016",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/enebolig_valkyrjegaten.jpg",
                    year: "2016",
                    type: "enebolig",
                    location: "",
                },
                {
                    fileName: "img/fritidsbolig_sele.jpg",
                    year: "2016",
                    type: "fritidsbolig",
                    location: "",
                },
                {
                    fileName: "img/fritidsbolig_vierneset.jpg",
                    year: "2016",
                    type: "fritidsbolif",
                    location: "",
                },
                {
                    fileName: "img/mindrebygg_bretlandsgaten.jpg",
                    year: "2016",
                    type: "mindre_bygg",
                    location: "",
                },
                {
                    fileName: "img/naering_sokn_camping.jpg",
                    year: "2017",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/naering_byggmestrenes_hus.jpg",
                    year: "2017",
                    type: "naering",
                    location: "",
                },
                {
                    fileName: "img/ideer_nabolaget_01.jpg",
                    year: "2017",
                    type: "ideer",
                    location: "",
                },
            ]
    }
